# Generated by Django 5.0.4 on 2024-05-06 10:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('trailer_url', models.URLField()),
                ('intro_notes', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('duration', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MofreyfxUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaidCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('courseId', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('courseId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('amountkes', models.FloatField(default=0.0)),
                ('amountusd', models.FloatField(default=0.0)),
                ('mpesa_number', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(default='initialized', max_length=20)),
                ('payment_method', models.CharField(default='mpesa', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(default='name', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField()),
                ('video_url', models.URLField()),
                ('module_notes', models.TextField(blank=True)),
                ('module_number', models.IntegerField(unique=True)),
                ('marks', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_image_url', models.URLField(default='https://me.com')),
                ('question_text', models.TextField()),
                ('choice1', models.CharField(blank=True, max_length=255)),
                ('choice2', models.CharField(max_length=255)),
                ('choice3', models.CharField(blank=True, max_length=255)),
                ('choice4', models.CharField(blank=True, max_length=255)),
                ('choice5', models.CharField(blank=True, max_length=255)),
                ('correct_answer', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('name', models.CharField(default='name', max_length=255)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.modules')),
            ],
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
        ),
        migrations.AddField(
            model_name='modules',
            name='subtopic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.subtopic'),
        ),
    ]
