# Generated by Django 3.2.6 on 2021-09-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='search',
            field=models.CharField(max_length=1000000),
        ),
    ]
