# Generated by Django 5.0.4 on 2024-05-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
