# Generated by Django 5.0.4 on 2024-05-06 10:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_image_url', models.URLField(default='https://me.com')),
                ('question_text', models.TextField()),
                ('choice1', models.CharField(blank=True, max_length=255)),
                ('choice2', models.CharField(max_length=255)),
                ('choice3', models.CharField(blank=True, max_length=255)),
                ('choice4', models.CharField(blank=True, max_length=255)),
                ('choice5', models.CharField(blank=True, max_length=255)),
                ('correct_answer', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('name', models.CharField(default='name', max_length=255)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.modules')),
            ],
        ),
    ]
