# Generated by Django 3.2.6 on 2021-09-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_words_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='search',
            field=models.CharField(max_length=50),
        ),
    ]
