# Generated by Django 5.0.4 on 2024-05-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_quiz_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='name',
        ),
    ]
