# Generated by Django 3.2.6 on 2021-09-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_words_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='search',
            field=models.TextField(max_length=10),
        ),
    ]
