# Generated by Django 5.0.4 on 2024-05-06 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_questions_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
    ]
