# Generated by Django 3.2.6 on 2021-09-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_words_search'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='Feature',
        ),
    ]
