# Generated by Django 3.2.6 on 2021-09-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_words_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='search',
            new_name='name',
        ),
    ]
