# Generated by Django 5.0.4 on 2024-05-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_marks_remove_modules_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
