# Generated by Django 5.0.4 on 2024-05-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_marks_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
