# Generated by Django 5.0.4 on 2024-05-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_marks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mofreyfxusers',
            name='firstname',
            field=models.CharField(default='firstname', max_length=20),
        ),
        migrations.AddField(
            model_name='mofreyfxusers',
            name='secondname',
            field=models.CharField(default='secondname', max_length=20),
        ),
        migrations.AlterField(
            model_name='modules',
            name='module_number',
            field=models.IntegerField(),
        ),
    ]
