# Generated by Django 5.0.4 on 2024-05-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_mofreyfxusers_firstname_mofreyfxusers_secondname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module_number',
            field=models.FloatField(),
        ),
    ]
