# Generated by Django 5.0.4 on 2024-05-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_modules_module_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module_number',
            field=models.IntegerField(),
        ),
    ]
