# Generated by Django 5.0.4 on 2024-05-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_modules_module_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mofreyfxusers',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mofreyfxusers',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mofreyfxusers',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
