# Generated by Django 3.0.1 on 2024-04-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_mpesapayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='amountkes',
            field=models.FloatField(),
        ),
    ]
