# Generated by Django 5.0.4 on 2024-06-04 11:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_mofreyfxusers_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='intro_notes',
            new_name='course_description',
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_name', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField()),
                ('video_url', models.URLField()),
                ('episode_notes', models.TextField(blank=True)),
                ('episode_number', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('subtopic', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.subtopic')),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.episodes'),
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
    ]
