# Generated by Django 5.0.4 on 2024-06-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_intro_notes_course_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_image_url',
            field=models.URLField(blank=True),
        ),
    ]
