# Generated by Django 3.0.1 on 2024-04-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20240422_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesapayment',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254),
        ),
    ]
