# Generated by Django 3.0.1 on 2024-04-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_mpesapayment_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='email@gmail.com', max_length=254)),
                ('courseId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('amountusd', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(default='initialized', max_length=20)),
            ],
        ),
    ]
