# Generated by Django 3.0.1 on 2024-04-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_cardpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardPayment',
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='amountusd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mpesapayment',
            name='payment_method',
            field=models.CharField(default='mpesa', max_length=20),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='amountkes',
            field=models.FloatField(default=0.0),
        ),
    ]
