# Generated by Django 3.0.1 on 2024-04-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20240423_0830'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MpesaPayment',
            new_name='Payments',
        ),
    ]
