# Generated by Django 3.0.1 on 2024-04-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20240423_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='mofrexusers',
            name='phone',
            field=models.CharField(default='0112345678', max_length=20),
        ),
        migrations.AddField(
            model_name='mofrexusers',
            name='username',
            field=models.CharField(default='username', max_length=20),
        ),
    ]
