# Generated by Django 3.0.1 on 2024-04-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20240423_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='choice3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='choice4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='choice5',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
