# Generated by Django 3.0.1 on 2024-04-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_auto_20240423_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choice4',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choice5',
        ),
    ]
