# Generated by Django 3.0.1 on 2024-04-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20240423_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='choice3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='questions',
            name='choice4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='questions',
            name='choice5',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
