# Generated by Django 3.0.1 on 2024-04-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20240423_1301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MofrexUsers',
            new_name='MofreyfxUsers',
        ),
    ]
